version: '3'


services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - static_volume:/usr/src/app/backend/static
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  

volumes:
  postgres_data:
  static_volume:
