# Generated by Django 5.0.4 on 2024-04-21 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtempcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authtempcode',
            name='retry_attempts',
            field=models.IntegerField(default=0, verbose_name='Количество повторных попыток'),
        ),
    ]
