# Generated by Django 5.0.4 on 2024-04-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_authtempcode_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtempcode',
            name='temp_code',
            field=models.CharField(max_length=4, verbose_name='Одноразовый код'),
        ),
    ]
